### ISSUE TITLE
Pulling 4.0.2 caused breakage

### ISSUE THREAD

**Issue by MacksMind** [celluloid/timers#53] opened 2015-08-31 15:48 UTC
Moving 4.0.2 to 4.1.0 caused `bundle install` breakage for anyone unlucky enough to implement Sidekiq while 4.0.2 existed, because celluloid 0.16.1 lists timers ~> 4.0.0 as a dependency. Undoubtedly there are other use cases as well.

Hand editing Gemfile.lock is a workaround, but maybe re-release 4.0.1 as 4.0.3 to provide an obvious resolution?

**Comment by ioquatix** [comment] 2015-09-01 00:10
Good idea.. @digitalextremist, can you sort this out?

**Comment by tarcieri** [comment] 2015-09-01 02:26
A 4.0.3 seems like the simplest way out of this quagmire despite whatever philosophical implications about semantic versioning.

**Comment by digitalextremist** [comment] 2015-09-01 05:31
In a few hours I will cut `4.1.0` as `4.0.3` also, rather than `4.0.1` being `4.0.3`

**Comment by digitalextremist** [comment] 2015-09-01 12:04
Actually, this will be `4.0.4` -- as a duplicate of `4.1.1`

**Comment by digitalextremist** [comment] 2015-09-01 12:06
The gem is about to be cut once the tests pass.

**Comment by digitalextremist** [comment] 2015-09-01 12:13
https://github.com/celluloid/timers/releases/tag/v4.0.4

**Closed by digitalextremist** 2015-09-01 12:13 UTC
